version: 2

mkdocs:
  configuration: mkdocs.yml

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

  jobs:
    post_create_environment:
      - pip install poetry
      - pip install mkdocs-material
      - pip install 'mkdocstrings[python]'
      - pip install mkdocs-mermaid2-plugin


    post_install:
      - poetry install --only doc