site_name: Projeto PII Brasil
repo_url: https://github.com/pedrohcmds/identificador-pii
repo_name: projeto-pii-brasil
edit_uri: tree/main/docs

theme:
  name: readthedocs
  language: pt-BR

markdown_extensions:
  - attr_list

extra_css:
  - stylesheets/extra.css



plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [identificador]
- mermaid2: